{% set version = "0.1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nardl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nardl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nardl/nardl_{{ version }}.tar.gz
  sha256: 35882ce3cd2c47f117a3741539ac46cf099bf0d44a9d60e6d84012fd498dc8ed

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-mass
    - r-car
    - r-gtools
    - r-strucchange
    - r-tseries
  run:
    - r-base
    - r-formula
    - r-mass
    - r-car
    - r-gtools
    - r-strucchange
    - r-tseries

test:
  commands:
    - $R -e "library('nardl')"           # [not win]
    - "\"%R%\" -e \"library('nardl')\""  # [win]

about:
  home: https://github.com/zedtaha/nardl
  license: GPL-3.0-only
  summary: Computes the nonlinear cointegrating autoregressive distributed lag model with p lags of the dependent variables and q lags of independent variables proposed by (Shin, Yu & Greenwood-Nimmo, 2014 <doi:10.1007/978-1-4899-8008-3_9>).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: nardl
# Type: Package
# Title: Nonlinear Cointegrating Autoregressive Distributed Lag Model
# Version: 0.1.5
# Author: Taha Zaghdoudi
# Maintainer: Taha Zaghdoudi <zedtaha@gmail.com>
# Description: Computes the nonlinear cointegrating autoregressive distributed lag model with p lags of the dependent variables and q lags of independent variables proposed by (Shin, Yu & Greenwood-Nimmo, 2014 <doi:10.1007/978-1-4899-8008-3_9>).
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# Imports: stats, strucchange, tseries, Formula, gtools
# Suggests: testthat
# BugReports: https://github.com/zedtaha/nardl/issues
# URL: https://github.com/zedtaha/nardl
# NeedsCompilation: no
# Packaged: 2018-05-07 16:29:31 UTC; Asus
# Repository: CRAN
# Date/Publication: 2018-05-07 17:03:14 UTC
